name: Update GEOIP_RU

on:
  workflow_dispatch:

  schedule:
    - cron: "15 3 * * *"

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh

      - name: Build
        run: |
          ./scripts/build.sh

      - name: Commit changes
        run: |

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output/

          if git diff --cached --quiet
          then
              echo "No changes."
              exit 0
          fi

          git commit -m "Update GEOIP_RU"

          git push
